### ISSUE TITLE
Unable to draw on Android Chrome Browser

### ISSUE THREAD

**Issue by Ben76** [jakubfiala/atrament#36]
I have a canvas in a Bootstrap Modal.

Works perfectly well on a PC; Not working on Android phone

Used to work well until Chrome released a new version for Android. (on 18th Oct)

Even now, if canvas placed directly on form, it works. Doesn't work when placed in Modal.

**Comment by jakubfiala** [comment]
@Ben76 thanks for submitting the issue. Can you see any errors being thrown in the console? Alternatively, can you create a codepen/jsbin that demonstrates the issue?

**Comment by bencergazda** [comment]
@Ben76 @jakubfiala I was having the same issue. In my case, it occured only when we needed to scroll downwards the page to the canvas. In this situation, the scrollTop gets added to the mouse position when drawing (see ` + document.documentElement.scrollLeft` in [src/atrament.js#L31](https://github.com/jakubfiala/atrament.js/blob/master/src/atrament.js#L31)). Like this, if we scroll down for 10px, and the start painting, the drawing appears 10px under the mouse cursor/touch point.

See: https://codepen.io/bencergazda/pen/OapvVL

I did a quick test with removing the addition of `document.documentElement.scrollLeft`. This fixes the issue on Mobile Chrome, and looks like not causing problems in other browsers (Firefox, Desktop Chrome, Mobile Safari)

I can make a pull request with a fix.

**Comment by jakubfiala** [comment]
thanks for submitting the PRs @bencergazda – and sorry I'm getting to this late!

both PRs are looking good – going to approve & merge, then test the changes and publish

**Comment by jakubfiala** [comment]
@viettq1986 thanks for reporting the issue. Could you please let me know how I can replicate the issue in your app? I'm having trouble finding the place where Atrament is used.

Also, what version of Android (and Chrome) are you using?

**Comment by viettq1986** [comment]
> @viettq1986 thanks for reporting the issue. Could you please let me know how I can replicate the issue in your app? I'm having trouble finding the place where Atrament is used.
> 
> Also, what version of Android (and Chrome) are you using?

Hello, Sorry for your Atrament.

Please see my step by step:

![image](https://user-images.githubusercontent.com/72916589/97809776-a1839680-1ca1-11eb-8fc1-e6e17e7365c2.png)

![image](https://user-images.githubusercontent.com/72916589/97809783-a9433b00-1ca1-11eb-90e5-60cfea105c45.png)

![image](https://user-images.githubusercontent.com/72916589/97809784-af391c00-1ca1-11eb-969f-892172b6bf5e.png)

![image](https://user-images.githubusercontent.com/72916589/97809791-b3fdd000-1ca1-11eb-9af5-cd359ae137f9.png)

I am using lasted android chrome version

![image](https://user-images.githubusercontent.com/72916589/97809844-1eaf0b80-1ca2-11eb-8fb1-624d2f7e20d0.png)

My function for get mouse and touch coordinates
getCoordinate = (e, canvas) => {
  let coordinate = {
    x: 0,
    y: 0
  };

  if (e.touches && e.touches.length > 0) {
    let touch = e.touches[0]; //Get the information for finger #1
    let rect = canvas.getBoundingClientRect();

    //coordinate.x = Math.floor((touch.pageX - rect.left) * (canvas.width / rect.width));
    //coordinate.y = Math.floor((touch.pageY - rect.top) * (canvas.height / rect.height));

    coordinate.x = Math.floor((touch.pageX - rect.left) * (canvas.width / rect.width));
    coordinate.y = Math.floor((touch.pageY - rect.top) * (canvas.height / rect.height));

    let matrix = canvas.getContext("2d").getTransform();
    let iMatrix = matrix.invertSelf();

    coordinate = applyToPoint(iMatrix, coordinate);
  } else {
    if (e.offsetX) {
      coordinate.x = e.offsetX;
      coordinate.y = e.offsetY;
    } else if (e.layerX) {
      coordinate.x = e.layerX;
      coordinate.y = e.layerY;
    } else if (e.clientX) {
      coordinate.x = e.clientX;
      coordinate.y = e.clientY;
    }
  }

  return coordinate;
}

Thank you very much

**Comment by jakubfiala** [comment]
@viettq1986 I believe your issue might be solved in v4.0.0 - please feel free to reopen if the issue occurs again
