### ISSUE TITLE
Just add some text labelling for drawings 

### ISSUE THREAD

**Issue by Easy-Cloud-in** [jakubfiala/atrament#96]

**Comment by jakubfiala** [comment]
@Easy-Cloud-in thank you for opening the issue! What exactly do you mean by text labelling?

**Comment by Easy-Cloud-in** [comment]
If a draw a design in the atrament i want to label it.  Let me be more specific, If we draw a cutting pattern, we like to name all the sides with a name and sizes for it.  so it will be use full for us.

**Comment by jakubfiala** [comment]
Thank you for clarifying. Atrament operates on the `<canvas>` element you provide to it, so you can paint anything you want on the canvas, in addition to the Atrament drawing. To paint text, you can use the `fillText` method of the canvas rendering context. See [here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text) for a guide on how to do that. If you want to automatically add labels to individual strokes produced by Atrament, you can determine the location of each stroke using the [strokerecorded](https://github.com/jakubfiala/atrament?tab=readme-ov-file#stroke-recording) event.

Hope that helps! I'm going to close the issue now, feel free to reopen it if you discover any issues.
