### ISSUE TITLE
Click creates a line in top left corner

### ISSUE THREAD

**Issue by nichoth** [jakubfiala/atrament#99]
1. Thanks for working in open source, this library is really cool.

2. When I click or double click in the middle of the canvas, it creates a diagonal line in the top left corner. This is visible in the demo page, https://www.fiala.space/atrament/demo/ , though it is hidden by the controls on the left.

<img width="1054" alt="image" src="https://github.com/jakubfiala/atrament/assets/5776508/a403daf5-e947-4bdf-a851-59b108b2249e">

**Comment by jakubfiala** [comment]
Hey there @nichoth! thank you very much for catching this bug and also opening a PR, really appreciate that :) I'll look at the fix now.
